"""Localized secondary UI messages; source, en, de, es, it, pt, nl, ar, zh, ja."""
LANGUAGES = ('en', 'de', 'es', 'it', 'pt', 'nl', 'ar', 'zh', 'ja')
DATA = r"""Onglet en attente|Pending tab|Wartender Tab|Pestaña pendiente|Scheda in attesa|Separador pendente|Wachtend tabblad|علامة تبويب معلقة|待加载标签页|待機中のタブ
Actualiser (F5)|Reload (F5)|Neu laden (F5)|Recargar (F5)|Ricarica (F5)|Recarregar (F5)|Vernieuwen (F5)|إعادة التحميل (F5)|重新加载 (F5)|再読み込み (F5)
Arrêter le chargement (Échap)|Stop loading (Esc)|Laden stoppen (Esc)|Detener carga (Esc)|Interrompi caricamento (Esc)|Parar carregamento (Esc)|Laden stoppen (Esc)|إيقاف التحميل (Esc)|停止加载 (Esc)|読み込みを停止 (Esc)
Ajouter aux favoris|Add bookmark|Lesezeichen hinzufügen|Añadir marcador|Aggiungi ai preferiti|Adicionar favorito|Bladwijzer toevoegen|إضافة إشارة مرجعية|添加书签|ブックマークに追加
Retirer des favoris|Remove bookmark|Lesezeichen entfernen|Quitar marcador|Rimuovi dai preferiti|Remover favorito|Bladwijzer verwijderen|إزالة الإشارة المرجعية|移除书签|ブックマークを削除
Nouvel onglet (Ctrl+T)|New tab (Ctrl+T)|Neuer Tab (Ctrl+T)|Nueva pestaña (Ctrl+T)|Nuova scheda (Ctrl+T)|Novo separador (Ctrl+T)|Nieuw tabblad (Ctrl+T)|علامة تبويب جديدة (Ctrl+T)|新标签页 (Ctrl+T)|新しいタブ (Ctrl+T)
Connexion HTTPS|HTTPS connection|HTTPS-Verbindung|Conexión HTTPS|Connessione HTTPS|Ligação HTTPS|HTTPS-verbinding|اتصال HTTPS|HTTPS 连接|HTTPS 接続
Connexion HTTP non chiffrée|Unencrypted HTTP connection|Unverschlüsselte HTTP-Verbindung|Conexión HTTP sin cifrar|Connessione HTTP non cifrata|Ligação HTTP não encriptada|Onversleutelde HTTP-verbinding|اتصال HTTP غير مشفر|未加密的 HTTP 连接|暗号化されていない HTTP 接続
Page interne|Internal page|Interne Seite|Página interna|Pagina interna|Página interna|Interne pagina|صفحة داخلية|内部页面|内部ページ
Protections activées — cliquer pour désactiver|Protections on — click to disable|Schutz aktiv — zum Deaktivieren klicken|Protecciones activas — clic para desactivar|Protezioni attive — clic per disattivare|Proteções ativas — clique para desativar|Bescherming aan — klik om uit te schakelen|الحماية مفعلة — انقر لتعطيلها|保护已开启 — 点击禁用|保護有効 — クリックで無効化
Protections désactivées — cliquer pour activer|Protections off — click to enable|Schutz inaktiv — zum Aktivieren klicken|Protecciones inactivas — clic para activar|Protezioni disattive — clic per attivare|Proteções inativas — clique para ativar|Bescherming uit — klik om in te schakelen|الحماية معطلة — انقر لتفعيلها|保护已关闭 — 点击启用|保護無効 — クリックで有効化
[Épinglé] |[Pinned] |[Angeheftet] |[Fijada] |[Bloccata] |[Fixado] |[Vastgezet] |[مثبت] |[已固定] |[固定] 
[Muet] |[Muted] |[Stumm] |[Silenciada] |[Audio disattivato] |[Sem som] |[Gedempt] |[صامت] |[静音] |[ミュート] 
Menu|Menu|Menü|Menú|Menu|Menu|Menu|القائمة|菜单|メニュー
Favori|Bookmark|Lesezeichen|Marcador|Preferito|Favorito|Bladwijzer|إشارة مرجعية|书签|ブックマーク
Protections|Protections|Schutz|Protecciones|Protezioni|Proteções|Bescherming|الحماية|保护|保護
Téléchargement|Download|Download|Descarga|Download|Transferência|Download|تنزيل|下载|ダウンロード
Téléchargement...|Downloading…|Wird heruntergeladen…|Descargando…|Download in corso…|A transferir…|Downloaden…|جارٍ التنزيل…|正在下载…|ダウンロード中…
Terminé · prêt à ouvrir|Complete · ready to open|Fertig · bereit zum Öffnen|Completado · listo para abrir|Completato · pronto da aprire|Concluído · pronto a abrir|Voltooid · klaar om te openen|اكتمل · جاهز للفتح|已完成 · 可以打开|完了 · 開けます
Annulé|Cancelled|Abgebrochen|Cancelado|Annullato|Cancelado|Geannuleerd|ملغى|已取消|キャンセル済み
Interrompu|Interrupted|Unterbrochen|Interrumpido|Interrotto|Interrompido|Onderbroken|متوقف|已中断|中断
Téléchargements : {count}|Downloads: {count}|Downloads: {count}|Descargas: {count}|Download: {count}|Transferências: {count}|Downloads: {count}|التنزيلات: {count}|下载：{count}|ダウンロード：{count}
Navigation privée|Private browsing|Privates Surfen|Navegación privada|Navigazione privata|Navegação privada|Privénavigatie|التصفح الخاص|隐私浏览|プライベートブラウジング
Profil actuel : |Current profile: |Aktuelles Profil: |Perfil actual: |Profilo attuale: |Perfil atual: |Huidig profiel: |الملف الشخصي الحالي: |当前个人资料：|現在のプロファイル：
Profil utilisé|Profile in use|Profil wird verwendet|Perfil en uso|Profilo in uso|Perfil em uso|Profiel in gebruik|الملف الشخصي قيد الاستخدام|个人资料正在使用|使用中のプロファイル
Impossible de supprimer le profil actuel.|Cannot delete the current profile.|Das aktuelle Profil kann nicht gelöscht werden.|No se puede eliminar el perfil actual.|Impossibile eliminare il profilo attuale.|Não é possível eliminar o perfil atual.|Het huidige profiel kan niet worden verwijderd.|لا يمكن حذف الملف الشخصي الحالي.|无法删除当前个人资料。|現在のプロファイルは削除できません。
Profil protégé|Protected profile|Geschütztes Profil|Perfil protegido|Profilo protetto|Perfil protegido|Beveiligd profiel|ملف شخصي محمي|受保护的个人资料|保護されたプロファイル
Le profil Default ne peut pas être supprimé.|The Default profile cannot be deleted.|Das Profil Default kann nicht gelöscht werden.|No se puede eliminar el perfil Default.|Il profilo Default non può essere eliminato.|O perfil Default não pode ser eliminado.|Het profiel Default kan niet worden verwijderd.|لا يمكن حذف الملف الشخصي Default.|无法删除 Default 个人资料。|Default プロファイルは削除できません。
Le nouveau profil sera utilisé au prochain démarrage.|The new profile will be used after restart.|Das neue Profil wird nach dem Neustart verwendet.|El nuevo perfil se usará al reiniciar.|Il nuovo profilo verrà usato dopo il riavvio.|O novo perfil será usado após reiniciar.|Het nieuwe profiel wordt na herstart gebruikt.|سيُستخدم الملف الشخصي الجديد بعد إعادة التشغيل.|重启后将使用新的个人资料。|新しいプロファイルは再起動後に使用されます。
Activer / Désactiver|Enable / Disable|Aktivieren / Deaktivieren|Activar / Desactivar|Attiva / Disattiva|Ativar / Desativar|Inschakelen / Uitschakelen|تفعيل / تعطيل|启用 / 禁用|有効 / 無効
Activée|Enabled|Aktiviert|Activada|Attivata|Ativada|Ingeschakeld|مفعلة|已启用|有効
Désactivée|Disabled|Deaktiviert|Desactivada|Disattivata|Desativada|Uitgeschakeld|معطلة|已禁用|無効
Aucune extension installée.|No extensions installed.|Keine Erweiterungen installiert.|No hay extensiones instaladas.|Nessuna estensione installata.|Sem extensões instaladas.|Geen extensies geïnstalleerd.|لا توجد إضافات مثبتة.|未安装扩展。|拡張機能がインストールされていません。
Choisir le dossier de l’extension|Choose the extension folder|Erweiterungsordner auswählen|Elegir carpeta de la extensión|Scegli la cartella dell’estensione|Escolher pasta da extensão|Extensiemap kiezen|اختيار مجلد الإضافة|选择扩展文件夹|拡張機能のフォルダーを選択
Installation impossible|Installation failed|Installation fehlgeschlagen|Error de instalación|Installazione non riuscita|Falha na instalação|Installatie mislukt|فشل التثبيت|安装失败|インストール失敗
Enregistrement impossible|Save failed|Speichern fehlgeschlagen|Error al guardar|Salvataggio non riuscito|Falha ao guardar|Opslaan mislukt|فشل الحفظ|保存失败|保存失敗
Extension installée|Extension installed|Erweiterung installiert|Extensión instalada|Estensione installata|Extensão instalada|Extensie geïnstalleerd|تم تثبيت الإضافة|扩展已安装|拡張機能をインストールしました
L’extension a été copiée et est désactivée. Cliquez sur Activer pour l’utiliser.|The extension was copied and is disabled. Click Enable to use it.|Die Erweiterung wurde kopiert und ist deaktiviert. Zum Verwenden aktivieren.|La extensión se copió y está desactivada. Actívala para usarla.|L’estensione è stata copiata ed è disattivata. Attivala per usarla.|A extensão foi copiada e está desativada. Ative-a para a usar.|De extensie is gekopieerd en uitgeschakeld. Schakel haar in om te gebruiken.|نُسخت الإضافة وهي معطلة. انقر على تفعيل لاستخدامها.|扩展已复制但未启用。点击启用以使用。|拡張機能をコピーしました。使用するには有効にしてください。
Activer cette extension ?|Enable this extension?|Diese Erweiterung aktivieren?|¿Activar esta extensión?|Attivare questa estensione?|Ativar esta extensão?|Deze extensie inschakelen?|هل تريد تفعيل هذه الإضافة؟|启用此扩展？|この拡張機能を有効にしますか？
Son script peut lire et modifier les pages visitées et envoyer des données sur Internet. Activez uniquement les extensions dont vous connaissez la provenance.|Its script can read and change visited pages and send data online. Only enable extensions you trust.|Das Skript kann besuchte Seiten lesen, ändern und Daten senden. Nur vertrauenswürdige Erweiterungen aktivieren.|Su script puede leer y modificar páginas y enviar datos. Activa solo extensiones de confianza.|Lo script può leggere e modificare pagine e inviare dati. Attiva solo estensioni affidabili.|O script pode ler e alterar páginas e enviar dados. Ative apenas extensões de confiança.|Het script kan pagina’s lezen, wijzigen en gegevens verzenden. Schakel alleen vertrouwde extensies in.|يمكن للبرنامج قراءة الصفحات وتعديلها وإرسال البيانات. فعّل الإضافات الموثوقة فقط.|脚本可读取和修改页面并发送数据。仅启用可信扩展。|スクリプトはページの読み取り、変更、データ送信が可能です。信頼する拡張機能のみ有効にしてください。
Effacer définitivement l’historique de ce profil ?|Permanently clear this profile’s history?|Verlauf dieses Profils endgültig löschen?|¿Borrar definitivamente el historial de este perfil?|Cancellare definitivamente la cronologia del profilo?|Eliminar permanentemente o histórico deste perfil?|Geschiedenis van dit profiel definitief wissen?|هل تريد مسح سجل هذا الملف الشخصي نهائيًا؟|永久清除此个人资料的历史记录？|このプロファイルの履歴を完全に消去しますか？
Supprimer les cookies de ce profil ? Cela déconnecte les sites.|Delete this profile’s cookies? This signs you out of websites.|Cookies dieses Profils löschen? Dadurch werden Sie von Websites abgemeldet.|¿Borrar cookies del perfil? Se cerrarán las sesiones de los sitios.|Eliminare i cookie del profilo? Verrai disconnesso dai siti.|Eliminar cookies do perfil? As sessões dos sites serão terminadas.|Cookies van dit profiel wissen? Je wordt bij websites afgemeld.|حذف ملفات ارتباط هذا الملف الشخصي؟ سيؤدي ذلك إلى تسجيل الخروج من المواقع.|删除此个人资料的 Cookie？这将退出网站登录。|このプロファイルの Cookie を削除しますか？サイトからログアウトされます。
La suppression des cookies a été demandée.|Cookie deletion requested.|Löschen der Cookies angefordert.|Se ha solicitado borrar las cookies.|Eliminazione dei cookie richiesta.|Eliminação de cookies solicitada.|Verwijderen van cookies aangevraagd.|طُلب حذف ملفات الارتباط.|已请求删除 Cookie。|Cookie の削除を要求しました。
Vider le cache de ce profil ?|Clear this profile’s cache?|Cache dieses Profils leeren?|¿Vaciar la caché de este perfil?|Svuotare la cache del profilo?|Limpar a cache deste perfil?|Cache van dit profiel wissen?|هل تريد مسح ذاكرة هذا الملف الشخصي المؤقتة؟|清除此个人资料的缓存？|このプロファイルのキャッシュを消去しますか？
Le nettoyage a été demandé et se poursuit en arrière-plan.|Cleanup requested; it continues in the background.|Bereinigung angefordert; sie läuft im Hintergrund.|Limpieza solicitada; continúa en segundo plano.|Pulizia richiesta; prosegue in background.|Limpeza solicitada; continua em segundo plano.|Opschonen aangevraagd; dit gaat op de achtergrond verder.|طُلب التنظيف ويستمر في الخلفية.|已请求清理，将在后台继续。|クリーンアップを要求しました。バックグラウンドで続行されます。
Rétablir les valeurs par défaut dans ce formulaire ? Cliquez ensuite sur Enregistrer pour les appliquer.|Reset this form to defaults? Click Save to apply.|Formular auf Standardwerte zurücksetzen? Zum Anwenden speichern.|¿Restablecer el formulario? Pulsa Guardar para aplicar.|Ripristinare i valori predefiniti? Premi Salva per applicare.|Restaurar predefinições? Clique em Guardar para aplicar.|Dit formulier herstellen naar standaardwaarden? Klik op Opslaan om toe te passen.|استعادة القيم الافتراضية للنموذج؟ انقر على حفظ لتطبيقها.|将此表单恢复为默认值？点击保存以应用。|このフォームを既定値に戻しますか？保存して適用してください。
Redémarrez Open Kitten pour appliquer la langue de l’interface.|Restart Open Kitten to apply the interface language.|Open Kitten neu starten, um die Sprache anzuwenden.|Reinicia Open Kitten para aplicar el idioma.|Riavvia Open Kitten per applicare la lingua.|Reinicie Open Kitten para aplicar o idioma.|Herstart Open Kitten om de taal toe te passen.|أعد تشغيل Open Kitten لتطبيق لغة الواجهة.|重启 Open Kitten 以应用界面语言。|表示言語を適用するには Open Kitten を再起動してください。
Redémarrez le navigateur pour appliquer le proxy.|Restart the browser to apply the proxy.|Browser neu starten, um den Proxy anzuwenden.|Reinicia el navegador para aplicar el proxy.|Riavvia il browser per applicare il proxy.|Reinicie o navegador para aplicar o proxy.|Herstart de browser om de proxy toe te passen.|أعد تشغيل المتصفح لتطبيق الوكيل.|重启浏览器以应用代理设置。|プロキシを適用するにはブラウザーを再起動してください。
Extensions mises à jour|Extensions updated|Erweiterungen aktualisiert|Extensiones actualizadas|Estensioni aggiornate|Extensões atualizadas|Extensies bijgewerkt|تم تحديث الإضافات|扩展已更新|拡張機能を更新しました
Les réglages sont enregistrés. Rechargez les sites déjà ouverts pour appliquer les scripts.|Settings saved. Reload open websites to apply scripts.|Gespeichert. Geöffnete Websites neu laden, um Skripte anzuwenden.|Configuración guardada. Recarga los sitios abiertos para aplicar scripts.|Impostazioni salvate. Ricarica i siti aperti per applicare gli script.|Definições guardadas. Recarregue os sites para aplicar os scripts.|Instellingen opgeslagen. Herlaad open websites om scripts toe te passen.|حُفظت الإعدادات. أعد تحميل المواقع المفتوحة لتطبيق البرامج.|设置已保存。重新加载已打开的网站以应用脚本。|設定を保存しました。スクリプトを適用するにはサイトを再読み込みしてください。
Installer un dossier…|Install a folder…|Ordner installieren…|Instalar carpeta…|Installa cartella…|Instalar pasta…|Map installeren…|تثبيت مجلد…|安装文件夹…|フォルダーをインストール…
Installer un ZIP…|Install a ZIP…|ZIP installieren…|Instalar ZIP…|Installa ZIP…|Instalar ZIP…|ZIP installeren…|تثبيت ZIP…|安装 ZIP…|ZIP をインストール…
Ouvrir l’extension|Open extension|Erweiterung öffnen|Abrir extensión|Apri estensione|Abrir extensão|Extensie openen|فتح الإضافة|打开扩展|拡張機能を開く
Désinstaller|Uninstall|Deinstallieren|Desinstalar|Disinstalla|Desinstalar|Verwijderen|إلغاء التثبيت|卸载|アンインストール
Extensions Chrome / Chromium|Chrome / Chromium extensions|Chrome-/Chromium-Erweiterungen|Extensiones Chrome / Chromium|Estensioni Chrome / Chromium|Extensões Chrome / Chromium|Chrome-/Chromium-extensies|إضافات Chrome / Chromium|Chrome / Chromium 扩展|Chrome / Chromium 拡張機能
Extensions Chrome / Chromium…|Chrome / Chromium extensions…|Chrome-/Chromium-Erweiterungen…|Extensiones Chrome / Chromium…|Estensioni Chrome / Chromium…|Extensões Chrome / Chromium…|Chrome-/Chromium-extensies…|إضافات Chrome / Chromium…|Chrome / Chromium 扩展…|Chrome / Chromium 拡張機能…
Dossier de l’extension Chromium|Chromium extension folder|Chromium-Erweiterungsordner|Carpeta de extensión Chromium|Cartella dell’estensione Chromium|Pasta da extensão Chromium|Chromium-extensiemap|مجلد إضافة Chromium|Chromium 扩展文件夹|Chromium 拡張機能フォルダー
Extension Chromium|Chromium extension|Chromium-Erweiterung|Extensión Chromium|Estensione Chromium|Extensão Chromium|Chromium-extensie|إضافة Chromium|Chromium 扩展|Chromium 拡張機能
Installer cette extension ?|Install this extension?|Diese Erweiterung installieren?|¿Instalar esta extensión?|Installare questa estensione?|Instalar esta extensão?|Deze extensie installeren?|هل تريد تثبيت هذه الإضافة؟|安装此扩展？|この拡張機能をインストールしますか？
Installation en cours…|Installing…|Wird installiert…|Instalando…|Installazione…|A instalar…|Installeren…|جارٍ التثبيت…|正在安装…|インストール中…
Opération terminée. Rechargez la page après activation.|Done. Reload the page after enabling.|Fertig. Seite nach Aktivierung neu laden.|Listo. Recarga la página tras activar.|Completato. Ricarica la pagina dopo l’attivazione.|Concluído. Recarregue a página após ativar.|Gereed. Herlaad de pagina na inschakelen.|اكتمل. أعد تحميل الصفحة بعد التفعيل.|操作完成。启用后请重新加载页面。|完了しました。有効化後にページを再読み込みしてください。
Supprimer cette extension du profil ?|Remove this extension from the profile?|Diese Erweiterung aus dem Profil entfernen?|¿Quitar esta extensión del perfil?|Rimuovere questa estensione dal profilo?|Remover esta extensão do perfil?|Deze extensie uit het profiel verwijderen?|هل تريد إزالة هذه الإضافة من الملف الشخصي؟|从个人资料中移除此扩展？|このプロファイルから拡張機能を削除しますか？
Aucune permission explicite|No explicit permissions|Keine ausdrücklichen Berechtigungen|Sin permisos explícitos|Nessuna autorizzazione esplicita|Sem permissões explícitas|Geen expliciete machtigingen|لا توجد أذونات صريحة|无明确权限|明示的な権限なし
\nPermissions déclarées :\n|\nDeclared permissions:\n|\nAngegebene Berechtigungen:\n|\nPermisos declarados:\n|\nAutorizzazioni dichiarate:\n|\nPermissões declaradas:\n|\nOpgegeven machtigingen:\n|\nالأذونات المعلنة:\n|\n声明的权限：\n|\n宣言された権限：\n
\nUne extension peut lire ou modifier les sites autorisés. Elle sera installée désactivée.|\nAn extension can read or modify permitted sites. It will be installed disabled.|\nEine Erweiterung kann erlaubte Websites lesen oder ändern. Sie wird deaktiviert installiert.|\nUna extensión puede leer o modificar sitios permitidos. Se instalará desactivada.|\nUn’estensione può leggere o modificare i siti consentiti. Sarà installata disattivata.|\nUma extensão pode ler ou alterar sites permitidos. Será instalada desativada.|\nEen extensie kan toegestane sites lezen of wijzigen. Ze wordt uitgeschakeld geïnstalleerd.|\nيمكن للإضافة قراءة المواقع المسموح بها أو تعديلها. ستُثبت معطلة.|\n扩展可以读取或修改获准的网站。安装后默认为禁用。|\n拡張機能は許可されたサイトを読み取り、変更できます。無効の状態でインストールされます。
Fonction indisponible : PyQt6-WebEngine et QtWebEngine 6.10 ou plus récents sont nécessaires.|Unavailable: PyQt6-WebEngine and QtWebEngine 6.10 or newer are required.|Nicht verfügbar: PyQt6-WebEngine und QtWebEngine ab 6.10 erforderlich.|No disponible: requiere PyQt6-WebEngine y QtWebEngine 6.10 o posteriores.|Non disponibile: servono PyQt6-WebEngine e QtWebEngine 6.10 o successivi.|Indisponível: requer PyQt6-WebEngine e QtWebEngine 6.10 ou posteriores.|Niet beschikbaar: PyQt6-WebEngine en QtWebEngine 6.10 of nieuwer vereist.|غير متاح: يتطلب PyQt6-WebEngine وQtWebEngine 6.10 أو أحدث.|不可用：需要 PyQt6-WebEngine 和 QtWebEngine 6.10 或更高版本。|使用不可：PyQt6-WebEngine と QtWebEngine 6.10 以降が必要です。
La précédente activation de cette extension ne s’est pas terminée. Activation bloquée pour éviter un nouveau crash. Vous pouvez la désinstaller.|The previous activation did not finish. Activation is blocked to prevent another crash. You can uninstall it.|Die vorige Aktivierung wurde nicht abgeschlossen. Zum Schutz vor Abstürzen gesperrt. Deinstallation ist möglich.|La activación anterior no terminó. Se bloquea para evitar otro fallo. Puedes desinstalarla.|L’attivazione precedente non è terminata. Bloccata per evitare altri arresti. Puoi disinstallarla.|A ativação anterior não terminou. Bloqueada para evitar nova falha. Pode desinstalar.|De vorige activering is niet voltooid. Geblokkeerd om een nieuwe crash te voorkomen. Verwijderen is mogelijk.|لم يكتمل التفعيل السابق. حُظر التفعيل لمنع تعطل جديد. يمكنك إلغاء التثبيت.|上次启用未完成。为防止再次崩溃，已阻止启用。可以卸载此扩展。|前回の有効化が完了しませんでした。再クラッシュ防止のためブロックしています。アンインストールは可能です。
Impossible de préparer le diagnostic : |Cannot prepare diagnostics: |Diagnose kann nicht vorbereitet werden: |No se puede preparar el diagnóstico: |Impossibile preparare la diagnostica: |Não foi possível preparar o diagnóstico: |Diagnose kan niet worden voorbereid: |تعذر إعداد التشخيص: |无法准备诊断：|診断を準備できません：
\nNavigateur expérimental basé sur QtWebEngine.|\nExperimental browser based on QtWebEngine.|\nExperimenteller Browser auf Basis von QtWebEngine.|\nNavegador experimental basado en QtWebEngine.|\nBrowser sperimentale basato su QtWebEngine.|\nNavegador experimental baseado em QtWebEngine.|\nExperimentele browser op basis van QtWebEngine.|\nمتصفح تجريبي مبني على QtWebEngine.|\n基于 QtWebEngine 的实验性浏览器。|\nQtWebEngine ベースの実験的なブラウザー。
Oui|Yes|Ja|Sí|Sì|Sim|Ja|نعم|是|はい
Non|No|Nein|No|No|Não|Nee|لا|否|いいえ
OK|OK|OK|Aceptar|OK|OK|OK|موافق|确定|OK
Cookies|Cookies|Cookies|Cookies|Cookie|Cookies|Cookies|ملفات الارتباط|Cookie|Cookie
Cache|Cache|Cache|Caché|Cache|Cache|Cache|الذاكرة المؤقتة|缓存|キャッシュ
Vos favoris apparaîtront ici.|Your bookmarks will appear here.|Ihre Lesezeichen erscheinen hier.|Tus marcadores aparecerán aquí.|I tuoi preferiti appariranno qui.|Os favoritos aparecerão aqui.|Je bladwijzers verschijnen hier.|ستظهر إشاراتك المرجعية هنا.|书签将显示在此处。|ブックマークはここに表示されます。
Ctrl + L pour la barre d’adresse · Ctrl + T pour un nouvel onglet|Ctrl + L for address bar · Ctrl + T for a new tab|Ctrl + L: Adressleiste · Ctrl + T: neuer Tab|Ctrl + L: dirección · Ctrl + T: nueva pestaña|Ctrl + L: indirizzo · Ctrl + T: nuova scheda|Ctrl + L: endereço · Ctrl + T: novo separador|Ctrl + L: adresbalk · Ctrl + T: nieuw tabblad|Ctrl + L لشريط العنوان · Ctrl + T لعلامة تبويب جديدة|Ctrl + L 地址栏 · Ctrl + T 新标签页|Ctrl + L：アドレスバー · Ctrl + T：新しいタブ
Activation : Menu → Extensions. Ces options ne changent pas les extensions activées. Après modification, rechargez les sites concernés. Les exceptions incluent les sous-domaines.|Enable via Menu → Extensions. These options do not enable extensions. Reload affected sites after changes. Exceptions include subdomains.|Aktivierung über Menü → Erweiterungen. Diese Optionen aktivieren nichts. Betroffene Seiten neu laden. Ausnahmen gelten auch für Subdomains.|Activa en Menú → Extensiones. Estas opciones no activan extensiones. Recarga los sitios tras cambios. Las excepciones incluyen subdominios.|Attiva da Menu → Estensioni. Queste opzioni non attivano estensioni. Ricarica i siti dopo le modifiche. Le eccezioni includono i sottodomini.|Ative em Menu → Extensões. Estas opções não ativam extensões. Recarregue os sites após alterações. As exceções incluem subdomínios.|Inschakelen via Menu → Extensies. Deze opties schakelen niets in. Herlaad sites na wijzigingen. Uitzonderingen omvatten subdomeinen.|التفعيل من القائمة ← الإضافات. هذه الخيارات لا تفعّل الإضافات. أعد تحميل المواقع بعد التغيير. تشمل الاستثناءات النطاقات الفرعية.|通过菜单 → 扩展启用。这些选项不会启用扩展。更改后请重新加载网站。例外包括子域名。|メニュー → 拡張機能で有効化します。この設定では有効化されません。変更後はサイトを再読み込みしてください。例外にはサブドメインも含まれます。
Extensions Open Kitten uniquement. Sélectionnez un dossier contenant manifest.json.\nAprès installation, activez l’extension puis fermez cette fenêtre pour l’appliquer.|Open Kitten extensions only. Select a folder containing manifest.json.\nAfter installation, enable the extension and close this window to apply it.|Nur Open-Kitten-Erweiterungen. Ordner mit manifest.json wählen.\nNach Installation aktivieren und Fenster schließen.|Solo extensiones Open Kitten. Selecciona una carpeta con manifest.json.\nTras instalar, activa la extensión y cierra la ventana.|Solo estensioni Open Kitten. Scegli una cartella con manifest.json.\nDopo l’installazione, attiva l’estensione e chiudi la finestra.|Apenas extensões Open Kitten. Escolha uma pasta com manifest.json.\nApós instalar, ative a extensão e feche a janela.|Alleen Open Kitten-extensies. Kies een map met manifest.json.\nSchakel de extensie na installatie in en sluit dit venster.|إضافات Open Kitten فقط. اختر مجلدًا يحتوي manifest.json.\nبعد التثبيت، فعّل الإضافة وأغلق النافذة لتطبيقها.|仅支持 Open Kitten 扩展。选择包含 manifest.json 的文件夹。\n安装后启用扩展并关闭此窗口以应用。|Open Kitten 拡張機能のみ。manifest.json を含むフォルダーを選択してください。\nインストール後に有効化し、このウィンドウを閉じて適用します。
Manifest V3 uniquement · Compatibilité selon les API utilisées.\nPour une extension Firefox, utilisez sa version Chromium.\nLes extensions installées sont désactivées au redémarrage : activez-les ici.|Manifest V3 only; compatibility depends on APIs used.\nFor Firefox extensions, use the Chromium version.\nInstalled extensions are disabled on restart; enable them here.|Nur Manifest V3; Kompatibilität hängt von den APIs ab.\nFür Firefox-Erweiterungen die Chromium-Version nutzen.\nNach Neustart hier erneut aktivieren.|Solo Manifest V3; compatibilidad según las API.\nPara Firefox, usa la versión Chromium.\nSe desactivan al reiniciar; actívalas aquí.|Solo Manifest V3; compatibilità secondo le API.\nPer Firefox, usa la versione Chromium.\nDisattivate al riavvio: riattivale qui.|Apenas Manifest V3; compatibilidade depende das APIs.\nPara Firefox, use a versão Chromium.\nDesativadas ao reiniciar: ative-as aqui.|Alleen Manifest V3; compatibiliteit hangt af van API’s.\nGebruik voor Firefox de Chromium-versie.\nUitgeschakeld bij herstart: schakel ze hier in.|Manifest V3 فقط؛ التوافق حسب الواجهات المستخدمة.\nلإضافات Firefox، استخدم نسخة Chromium.\nتُعطل عند إعادة التشغيل: فعّلها هنا.|仅支持 Manifest V3；兼容性取决于使用的 API。\nFirefox 扩展请使用 Chromium 版本。\n重启后扩展会禁用，请在此启用。|Manifest V3 のみ。互換性は使用 API に依存します。\nFirefox 拡張機能は Chromium 版を使用してください。\n再起動時は無効になります。ここで有効化してください。"""
MESSAGES = {}
for row in DATA.splitlines():
    fields = [value.replace(r'\n', '\n') for value in row.split('|')]
    if len(fields) != 10:
        raise ValueError('Invalid message row: ' + fields[0])
    MESSAGES[fields[0]] = dict(zip(LANGUAGES, fields[1:]))
