"""Localized validation messages and built-in extension metadata."""
from core.translation_messages import LANGUAGES
DATA = r"""Le fichier de paramètres doit contenir un objet.|Settings must contain a JSON object.|Einstellungen müssen ein JSON-Objekt enthalten.|La configuración debe contener un objeto JSON.|Le impostazioni devono contenere un oggetto JSON.|As definições devem conter um objeto JSON.|Instellingen moeten een JSON-object bevatten.|يجب أن تحتوي الإعدادات على كائن JSON.|设置必须包含 JSON 对象。|設定には JSON オブジェクトが必要です。
Valeur incorrecte : |Invalid value: |Ungültiger Wert: |Valor no válido: |Valore non valido: |Valor inválido: |Ongeldige waarde: |قيمة غير صالحة: |无效值：|無効な値：
Choix incorrect : |Invalid choice: |Ungültige Auswahl: |Opción no válida: |Scelta non valida: |Escolha inválida: |Ongeldige keuze: |اختيار غير صالح: |无效选项：|無効な選択：
Code de langue invalide.|Invalid language code.|Ungültiger Sprachcode.|Código de idioma no válido.|Codice lingua non valido.|Código de idioma inválido.|Ongeldige taalcode.|رمز لغة غير صالح.|无效的语言代码。|無効な言語コードです。
{key} doit être compris entre {low} et {high}.|{key} must be between {low} and {high}.|{key} muss zwischen {low} und {high} liegen.|{key} debe estar entre {low} y {high}.|{key} deve essere tra {low} e {high}.|{key} deve estar entre {low} e {high}.|{key} moet tussen {low} en {high} liggen.|يجب أن تكون {key} بين {low} و{high}.|{key} 必须介于 {low} 和 {high} 之间。|{key} は {low} から {high} の範囲で指定してください。
La page d’accueil doit être une adresse http:// ou https:// valide.|The home page must be a valid http:// or https:// address.|Die Startseite muss eine gültige http://- oder https://-Adresse sein.|El inicio debe ser una dirección http:// o https:// válida.|La pagina iniziale deve essere un indirizzo http:// o https:// valido.|A página inicial deve ser um endereço http:// ou https:// válido.|De startpagina moet een geldig http://- of https://-adres zijn.|يجب أن تكون الصفحة الرئيسية عنوان http:// أو https:// صالحًا.|主页必须是有效的 http:// 或 https:// 地址。|ホームページには有効な http:// または https:// アドレスが必要です。
Adresse du proxy incorrecte (sans protocole ni chemin).|Invalid proxy address (no protocol or path).|Ungültige Proxyadresse (ohne Protokoll oder Pfad).|Dirección de proxy no válida (sin protocolo ni ruta).|Indirizzo proxy non valido (senza protocollo o percorso).|Endereço proxy inválido (sem protocolo ou caminho).|Ongeldig proxyadres (zonder protocol of pad).|عنوان وكيل غير صالح (دون بروتوكول أو مسار).|无效代理地址（不含协议或路径）。|無効なプロキシアドレスです（プロトコルとパスは不要）。
Le port du proxy doit être compris entre 1 et 65535.|Proxy port must be between 1 and 65535.|Proxyport muss zwischen 1 und 65535 liegen.|El puerto debe estar entre 1 y 65535.|La porta deve essere tra 1 e 65535.|A porta deve estar entre 1 e 65535.|De proxypoort moet tussen 1 en 65535 liggen.|يجب أن يكون منفذ الوكيل بين 1 و65535.|代理端口必须介于 1 和 65535 之间。|プロキシのポートは 1～65535 で指定してください。
Exceptions : saisir des domaines sans https://, chemin ni joker.|Exceptions: enter domains without https://, paths or wildcards.|Ausnahmen: Domains ohne https://, Pfad oder Platzhalter eingeben.|Excepciones: dominios sin https://, rutas ni comodines.|Eccezioni: domini senza https://, percorsi o caratteri jolly.|Exceções: domínios sem https://, caminhos ou curingas.|Uitzonderingen: domeinen zonder https://, pad of jokertekens.|الاستثناءات: أدخل نطاقات دون https:// أو مسارات أو أحرف بدل.|例外：请输入不含 https://、路径或通配符的域名。|例外には https://、パス、ワイルドカードを含めずドメインを入力してください。
Maximum 100 domaines par liste d’exceptions.|Maximum 100 domains per exception list.|Maximal 100 Domains pro Ausnahmeliste.|Máximo 100 dominios por lista.|Massimo 100 domini per elenco.|Máximo de 100 domínios por lista.|Maximaal 100 domeinen per uitzonderingslijst.|الحد الأقصى 100 نطاق لكل قائمة استثناءات.|每个例外列表最多 100 个域名。|例外リストは最大 100 ドメインです。
Le manifeste doit être dans le dossier sélectionné.|The manifest must be inside the selected folder.|Das Manifest muss im ausgewählten Ordner liegen.|El manifiesto debe estar en la carpeta elegida.|Il manifest deve essere nella cartella selezionata.|O manifesto deve estar na pasta selecionada.|Het manifest moet in de geselecteerde map staan.|يجب أن يكون الملف التعريفي داخل المجلد المحدد.|清单必须位于所选文件夹内。|マニフェストは選択したフォルダー内に必要です。
Manifeste trop volumineux (64 Ko maximum).|Manifest too large (maximum 64 KB).|Manifest zu groß (maximal 64 KB).|Manifiesto demasiado grande (máximo 64 KB).|Manifest troppo grande (massimo 64 KB).|Manifesto demasiado grande (máximo 64 KB).|Manifest te groot (maximaal 64 KB).|الملف التعريفي كبير جدًا (64 كيلوبايت كحد أقصى).|清单过大（最大 64 KB）。|マニフェストが大きすぎます（最大 64 KB）。
Le manifeste doit être un objet JSON.|The manifest must be a JSON object.|Das Manifest muss ein JSON-Objekt sein.|El manifiesto debe ser un objeto JSON.|Il manifest deve essere un oggetto JSON.|O manifesto deve ser um objeto JSON.|Het manifest moet een JSON-object zijn.|يجب أن يكون الملف التعريفي كائن JSON.|清单必须是 JSON 对象。|マニフェストは JSON オブジェクトである必要があります。
Format non pris en charge. Utilisez un manifeste MiniBrowser, pas Chrome/Firefox.|Unsupported format. Use an Open Kitten manifest, not Chrome/Firefox.|Format nicht unterstützt. Open-Kitten-Manifest statt Chrome/Firefox verwenden.|Formato no admitido. Usa un manifiesto Open Kitten, no Chrome/Firefox.|Formato non supportato. Usa un manifest Open Kitten, non Chrome/Firefox.|Formato não suportado. Use manifesto Open Kitten, não Chrome/Firefox.|Formaat niet ondersteund. Gebruik een Open Kitten-manifest, geen Chrome/Firefox.|صيغة غير مدعومة. استخدم ملف Open Kitten وليس Chrome/Firefox.|不支持此格式。请使用 Open Kitten 清单，而非 Chrome/Firefox。|未対応の形式です。Chrome/Firefox ではなく Open Kitten のマニフェストを使用してください。
Champ invalide : |Invalid field: |Ungültiges Feld: |Campo no válido: |Campo non valido: |Campo inválido: |Ongeldig veld: |حقل غير صالح: |无效字段：|無効なフィールド：
enabled_by_default doit être un booléen.|enabled_by_default must be a boolean.|enabled_by_default muss ein boolescher Wert sein.|enabled_by_default debe ser booleano.|enabled_by_default deve essere booleano.|enabled_by_default deve ser booleano.|enabled_by_default moet een booleaanse waarde zijn.|يجب أن تكون enabled_by_default قيمة منطقية.|enabled_by_default 必须是布尔值。|enabled_by_default は真偽値である必要があります。
Liste de domaines invalide.|Invalid domain list.|Ungültige Domainliste.|Lista de dominios no válida.|Elenco domini non valido.|Lista de domínios inválida.|Ongeldige domeinlijst.|قائمة نطاقات غير صالحة.|无效的域名列表。|無効なドメインリストです。
Domaine invalide : utiliser un domaine en minuscules, sans URL ni joker.|Invalid domain: use lowercase, without URL or wildcards.|Ungültige Domain: Kleinschreibung, ohne URL oder Platzhalter.|Dominio no válido: usa minúsculas, sin URL ni comodines.|Dominio non valido: usa minuscole, senza URL o caratteri jolly.|Domínio inválido: use minúsculas, sem URL ou curingas.|Ongeldig domein: gebruik kleine letters, zonder URL of jokertekens.|نطاق غير صالح: استخدم أحرفًا صغيرة دون رابط أو أحرف بدل.|域名无效：请使用小写，不含 URL 或通配符。|無効なドメインです。小文字で入力し、URL やワイルドカードは含めないでください。
Nom de script invalide.|Invalid script name.|Ungültiger Skriptname.|Nombre de script no válido.|Nome script non valido.|Nome de script inválido.|Ongeldige scriptnaam.|اسم برنامج غير صالح.|无效的脚本名称。|無効なスクリプト名です。
Le script doit être un fichier .js directement dans le dossier.|The script must be a .js file directly in the folder.|Das Skript muss eine .js-Datei direkt im Ordner sein.|El script debe ser un archivo .js directamente en la carpeta.|Lo script deve essere un file .js direttamente nella cartella.|O script deve ser um ficheiro .js diretamente na pasta.|Het script moet een .js-bestand direct in de map zijn.|يجب أن يكون البرنامج ملف .js داخل المجلد مباشرة.|脚本必须是直接位于文件夹中的 .js 文件。|スクリプトはフォルダー直下の .js ファイルである必要があります。
Le script ne peut pas être un lien externe.|The script cannot be an external link.|Das Skript darf kein externer Link sein.|El script no puede ser un enlace externo.|Lo script non può essere un collegamento esterno.|O script não pode ser uma ligação externa.|Het script mag geen externe koppeling zijn.|لا يمكن أن يكون البرنامج رابطًا خارجيًا.|脚本不能是外部链接。|スクリプトを外部リンクにはできません。
Script trop volumineux (1 Mo maximum).|Script too large (maximum 1 MB).|Skript zu groß (maximal 1 MB).|Script demasiado grande (máximo 1 MB).|Script troppo grande (massimo 1 MB).|Script demasiado grande (máximo 1 MB).|Script te groot (maximaal 1 MB).|البرنامج كبير جدًا (1 ميغابايت كحد أقصى).|脚本过大（最大 1 MB）。|スクリプトが大きすぎます（最大 1 MB）。
Ajoutez un script ou des domaines à bloquer.|Add a script or domains to block.|Skript oder zu blockierende Domains hinzufügen.|Añade un script o dominios para bloquear.|Aggiungi uno script o domini da bloccare.|Adicione um script ou domínios a bloquear.|Voeg een script of te blokkeren domeinen toe.|أضف برنامجًا أو نطاقات لحظرها.|请添加脚本或要拦截的域名。|スクリプトまたはブロックするドメインを追加してください。
Cette version de cette extension est déjà installée.|This extension version is already installed.|Diese Erweiterungsversion ist bereits installiert.|Esta versión de la extensión ya está instalada.|Questa versione dell’estensione è già installata.|Esta versão da extensão já está instalada.|Deze extensieversie is al geïnstalleerd.|هذا الإصدار من الإضافة مثبت بالفعل.|此版本的扩展已安装。|このバージョンの拡張機能はインストール済みです。
Manifeste trop volumineux.|Manifest too large.|Manifest zu groß.|Manifiesto demasiado grande.|Manifest troppo grande.|Manifesto demasiado grande.|Manifest te groot.|الملف التعريفي كبير جدًا.|清单过大。|マニフェストが大きすぎます。
Archive trop volumineuse (100 Mo décompressés maximum).|Archive too large (maximum 100 MB unpacked).|Archiv zu groß (maximal 100 MB entpackt).|Archivo demasiado grande (máximo 100 MB descomprimido).|Archivio troppo grande (massimo 100 MB estratti).|Arquivo demasiado grande (máximo 100 MB descomprimidos).|Archief te groot (maximaal 100 MB uitgepakt).|الأرشيف كبير جدًا (100 ميغابايت بعد الفك كحد أقصى).|压缩包过大（解压后最大 100 MB）。|アーカイブが大きすぎます（展開後最大 100 MB）。
Chemin non autorisé dans l’archive.|Disallowed path in archive.|Unzulässiger Pfad im Archiv.|Ruta no permitida en el archivo.|Percorso non consentito nell’archivio.|Caminho não permitido no arquivo.|Niet-toegestaan pad in archief.|مسار غير مسموح في الأرشيف.|压缩包中含有不允许的路径。|アーカイブに許可されていないパスがあります。
Les liens symboliques ne sont pas autorisés.|Symbolic links are not allowed.|Symbolische Links sind nicht erlaubt.|No se permiten enlaces simbólicos.|I collegamenti simbolici non sono consentiti.|Ligações simbólicas não são permitidas.|Symbolische koppelingen zijn niet toegestaan.|الروابط الرمزية غير مسموحة.|不允许符号链接。|シンボリックリンクは許可されていません。
Un manifest.json est requis à la racine du ZIP.|A manifest.json is required at the ZIP root.|manifest.json muss im ZIP-Stammverzeichnis liegen.|Se requiere manifest.json en la raíz del ZIP.|È richiesto manifest.json nella radice dello ZIP.|É necessário manifest.json na raiz do ZIP.|manifest.json moet in de hoofdmap van de ZIP staan.|يجب وجود manifest.json في جذر ZIP.|ZIP 根目录需要 manifest.json。|ZIP のルートに manifest.json が必要です。
Choisissez un dossier ou un ZIP de la version Chrome/Chromium. CRX et XPI non pris en charge.|Choose a Chrome/Chromium folder or ZIP. CRX and XPI are unsupported.|Chrome-/Chromium-Ordner oder ZIP wählen. CRX und XPI werden nicht unterstützt.|Elige carpeta o ZIP de Chrome/Chromium. CRX y XPI no se admiten.|Scegli cartella o ZIP Chrome/Chromium. CRX e XPI non supportati.|Escolha pasta ou ZIP Chrome/Chromium. CRX e XPI não suportados.|Kies een Chrome/Chromium-map of ZIP. CRX en XPI niet ondersteund.|اختر مجلدًا أو ZIP لنسخة Chrome/Chromium. لا يُدعم CRX وXPI.|请选择 Chrome/Chromium 文件夹或 ZIP。不支持 CRX 和 XPI。|Chrome/Chromium 版のフォルダーか ZIP を選択してください。CRX と XPI は未対応です。
Le moteur accepte uniquement les extensions Manifest V3. Manifest V2 non pris en charge.|Only Manifest V3 extensions are supported, not Manifest V2.|Nur Manifest V3 wird unterstützt, nicht Manifest V2.|Solo se admite Manifest V3, no Manifest V2.|Supportato solo Manifest V3, non Manifest V2.|Apenas Manifest V3 é suportado, não Manifest V2.|Alleen Manifest V3 wordt ondersteund, niet Manifest V2.|يُدعم Manifest V3 فقط، وليس Manifest V2.|仅支持 Manifest V3，不支持 Manifest V2。|Manifest V3 のみ対応しています。Manifest V2 は未対応です。
Nom ou version manquant dans le manifeste.|Manifest name or version missing.|Name oder Version im Manifest fehlt.|Falta nombre o versión en el manifiesto.|Nome o versione mancanti nel manifest.|Falta nome ou versão no manifesto.|Naam of versie ontbreekt in manifest.|الاسم أو الإصدار مفقود في الملف التعريفي.|清单缺少名称或版本。|マニフェストに名前またはバージョンがありません。
Ce paquet cible Firefox. Utilisez sa version Chrome/Chromium Manifest V3.|This package targets Firefox. Use its Chrome/Chromium Manifest V3 version.|Dieses Paket ist für Firefox. Chrome-/Chromium-Version mit Manifest V3 verwenden.|Este paquete es para Firefox. Usa la versión Chrome/Chromium Manifest V3.|Pacchetto per Firefox. Usa la versione Chrome/Chromium Manifest V3.|Pacote para Firefox. Use a versão Chrome/Chromium Manifest V3.|Dit pakket is voor Firefox. Gebruik de Chrome/Chromium Manifest V3-versie.|هذه الحزمة لـFirefox. استخدم نسختها Chrome/Chromium Manifest V3.|此包适用于 Firefox。请使用其 Chrome/Chromium Manifest V3 版本。|Firefox 向けのパッケージです。Chrome/Chromium の Manifest V3 版を使用してください。
Permissions invalides.|Invalid permissions.|Ungültige Berechtigungen.|Permisos no válidos.|Autorizzazioni non valide.|Permissões inválidas.|Ongeldige machtigingen.|أذونات غير صالحة.|无效权限。|無効な権限です。
Ad Blocker|Ad Blocker|Werbeblocker|Bloqueador de anuncios|Blocco pubblicità|Bloqueador de anúncios|Advertentieblokker|مانع الإعلانات|广告拦截|広告ブロック
Privacy Guard|Privacy Guard|Datenschutz|Protector de privacidad|Protezione privacy|Proteção de privacidade|Privacybescherming|حماية الخصوصية|隐私防护|プライバシー保護
Dark Mode|Dark Mode|Dunkelmodus|Modo oscuro|Modalità scura|Modo escuro|Donkere modus|الوضع الداكن|深色模式|ダークモード
Filtrage réseau et masquage ciblé des emplacements publicitaires. Exceptions par site dans les paramètres.|Network filtering and targeted ad hiding. Per-site exceptions in settings.|Netzwerkfilter und gezieltes Ausblenden von Werbung. Website-Ausnahmen in den Einstellungen.|Filtrado de red y ocultación de anuncios. Excepciones por sitio en ajustes.|Filtro di rete e mascheramento pubblicità. Eccezioni per sito nelle impostazioni.|Filtragem de rede e ocultação de anúncios. Exceções por site nas definições.|Netwerkfilter en gericht advertenties verbergen. Website-uitzonderingen in instellingen.|تصفية الشبكة وإخفاء الإعلانات المحددة. استثناءات المواقع في الإعدادات.|网络过滤和定向隐藏广告。可在设置中添加网站例外。|ネットワークフィルターと広告枠の非表示。設定でサイトごとの例外を指定できます。
Filtrage des domaines de suivi, retrait des pings de liens et protection des liens externes. Exceptions par site.|Tracking-domain filtering, link ping removal and external-link protection. Per-site exceptions.|Tracker-Domainfilter, Entfernen von Link-Pings und Schutz externer Links. Website-Ausnahmen.|Filtrado de rastreadores, eliminación de pings y protección de enlaces externos. Excepciones por sitio.|Filtro dei tracker, rimozione ping e protezione link esterni. Eccezioni per sito.|Filtro de rastreadores, remoção de pings e proteção de ligações externas. Exceções por site.|Trackerfilter, link-pings verwijderen en externe links beschermen. Uitzonderingen per site.|تصفية نطاقات التتبع وإزالة إشارات الروابط وحماية الروابط الخارجية. استثناءات لكل موقع.|过滤跟踪域名、移除链接 ping 并保护外部链接。支持网站例外。|追跡ドメインのフィルター、リンク ping の削除、外部リンクの保護。サイトごとの例外に対応。
Thème sombre sans inversion des images, palette neutre ou chaude, respect du thème natif et exceptions par site.|Dark theme without inverting images, neutral or warm palette, native-theme detection and site exceptions.|Dunkles Design ohne Bildumkehr, neutrale oder warme Palette, Erkennung dunkler Seiten und Website-Ausnahmen.|Tema oscuro sin invertir imágenes, paleta neutra o cálida, detección de tema nativo y excepciones.|Tema scuro senza invertire immagini, tavolozza neutra o calda, riconoscimento tema nativo ed eccezioni.|Tema escuro sem inverter imagens, paleta neutra ou quente, deteção de tema nativo e exceções.|Donker thema zonder beeldomkering, neutraal of warm palet, themadetectie en site-uitzonderingen.|سمة داكنة دون عكس الصور، ألوان محايدة أو دافئة، اكتشاف السمة الأصلية واستثناءات المواقع.|不反转图像的深色主题，中性或暖色配色、原生主题检测和网站例外。|画像を反転しないダークテーマ。中性・暖色配色、既存テーマの検出、サイト例外に対応。"""
MESSAGES = {}
for row in DATA.splitlines():
    fields = row.split('|')
    if len(fields) != 10:
        raise ValueError('Invalid error translation row: ' + fields[0])
    MESSAGES[fields[0]] = dict(zip(LANGUAGES, fields[1:]))
